project:
  type: book
  output-dir: _site

lang: et

book:
  title: "Mikroökonoomika"
  author: "Maailmapilt"
  chapters:
    - index.qmd
    - peatukid/noudlus-pakkumine.qmd
    - peatukid/elastsus.qmd
    
format:
  html:
    theme: sandstone
      - assets/design.css
      - styles.css
    toc: true
